<?php

/**
 * @file tbx_file_field.module
 * TODO: Enter file description here.
 */



function tbx_file_field_preprocess_node (&$vars) {
	//kpr($vars);
	if(!user_is_logged_in()) { # don't show file field
	  $fields = field_read_fields(array('type' => 'file'));
	  $field_names = array_keys($fields);
	  foreach ($field_names as $field_name) {      	
	  	if(!empty($vars[$field_name])) {
	  		hide($vars['content'][$field_name]);
	  	}
	  }
	} 
}

